### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by MrYuion**
I've done a major cleanup of the logic, fixed some minor issues, and added dynamic text rendering.
Any feedback on things that could be improved would be appreciated.
You can run the demo with `gulp serve` to test it.

### CODE REVIEW

**Comment by w-le** [comment]
sounds amazeballs, I'll try it out this week.

**Comment by w-le** [comment]
is there any way to try it out inside another app without releasing a new version of the npm package?

**Comment by w-le** [comment]
- Looks good, zooming in doesn't cause pixelation like it sometimes does in the current master branch 👍 
- dynamic text rendering is awesome. Gonna save us (or at least me) HEAPS of time.

- While zoomed in, Adding a pin pans to the pin correctly, but adding a radius not pan to the radius. If the radius appears outside of the zoomed in viewable area, the user won't know that a radius was added.

- in this version the mouse scroll zoom is reverted back to the old mapping again. The new zoom mapping makes so much more sense. Do ensure that when merged into master, the zoom mapping is same as in master currently (fixed recently in: https://github.com/acaprojects/ngx-interactive-map/commit/9e69b17fe72fed3e2597353cfec03efb1b34e928)

**Comment by MrYuion** [comment]
Weird. For me to scrolling direction matches Google Maps. For the focusing I haven't setup any for the radiuses. I was thinking of making it so that overlayed components can't be placed outside the bounds of the map.

**Comment by w-le** [comment]
re: scroll zoom mapping: Oh you're right! sorry I was testing very late at night 😅 
Yep so keep that mapping as it is currently in this branch

**Comment by wle-aca** [comment]
re: scroll zoom mapping: Oh you're right! sorry I was testing very late at night 😅 
Yep so keep that mapping as it is currently in this branch

**Pull request merged**
